apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 3
  template:
    metadata:
      name: kube-testing
      labels:
        app: kube-testing
    spec:
      containers:
      - image: jonbaier/pod-scaling:0.1
        name: webserver

---
apiVersion: v1
kind: Service
metadata:
  name: demo-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30123
  selector:
    app: kube-testing
